### ISSUE TITLE
When the package name and  name defined in BUILD file are different exception is thrown.

### ISSUE THREAD

**Issue by jayachathu** [salesforce/pomgen#123]
This is the command I am trying to run.
 bazel run @pomgen//:pomgen -- --package //netld/bridge.collection --destdir /tmp/pomgen
bridge.collection is the folder name and the name  in BUILD file is defined as com-dancer-bridge-collection. When I run the above command it gives below error.

 File "/private/var/tmp/_bazel_chathu/681a4c112378bf4b2da36e5277bd43ac/external/pomgen/crawl/pom.py", line 746, in _query_dependencies
    raise Exception("Error while processing dependencies: %s %s caused by %s" % (msg, artifact_def, repr(e)))
Exception: Error while processing dependencies: <class 'subprocess.CalledProcessError'> com-dancer-bridge-collection:netld caused by CalledProcessError(7, "bazel query --noimplicit_deps --order_output full 'labels(deps, netld/bridge.collection:bridge.collection) union labels(runtime_deps, netld/bridge.collection:bridge.collection)'", '')

And if I just run the bazel command as below from the command line it succeds.

bazel query --noimplicit_deps --order_output full 'labels(deps, netld/bridge.collection:com-dancer-bridge-collection) union labels(runtime_deps, netld/bridge.collection:com-dancer-bridge-collection)'

**Comment by simontoens** [comment]
Hi @jayachathu, could you try renaming the `java_library` target in the BUILD file to `bridge.collection`?  pomgen is looking for the default target, so the target name should match the name of the directory its BUILD file lives in.  I think we need to document that better.

Example: https://github.com/salesforce/pomgen/blob/master/examples/hello-world/juicer/BUILD#L2

It wouldn't be too hard to make this customizable, but right now this behavior is just hardcoded.
