### ISSUE TITLE
Allow multiple versions of the same external maven jar to be used in a WORKSPACE

### ISSUE THREAD

**Issue by plaird** [salesforce/pomgen#40]
We have two services: PizzaService and TacoService. Both depend on the same jar from Maven: CheeseLib

Unfortunately, for a window of time, the services need different versions of CheeseLib. We model that in our WORKSPACE by giving the two different versions of the CheeseLib different names in Bazel. Then, PizzaService can use CheeseLib:1.0.0 and TacoService can use CheeseLib:2.0.0. This works for the Bazel side of things.

But pomgen broke. It assumes there is a single version of each Maven dep. I created a workaround in a branch:
https://github.com/salesforce/pomgen/tree/plaird/allow_conflicting_externals

The workaround is sufficient, in that pomgen doesn't fail with a fatal error. But it loses track of which specific version of CheeseLib each service needs. It just uses the version of the first one it finds in the WORKSPACE.

We need to decide:
1. is this a valid use case; do we see this in the wild with public Bazel repos?
2. how to solve this in a robust way

https://github.com/bazelbuild/rules_jvm_external#resolving-user-specified-and-transitive-dependency-version-conflicts

**Comment by btbuxton** [comment]
I'm moving the dependencies to be fully qualified in pomgen in maven_install branch. Thus, if multiple versions are needed, then a new maven_install rule could be created with new version. 

For example, call the maven_install rule "staging" then version 2.0 of CheeseLib could be in staging and the previous version in maven_install rule "maven". Thus, if the rule name is fully qualified in the template, the right version will be produced.

Does that make sense? If not,  I can expand further.

**Comment by simontoens** [comment]
Sounds good - I don't think there's a technical reason why pomgen couldn't keep track of multiple versions for the same lib - that shouldn't be hard to get to work.  The reason pomgen disallowed it is only because we didn't have that use-case before.

**Comment by simontoens** [comment]
This is supported now, by using the maven_install rule name in the version reference syntax:
```
#{@rule1//:commons_lang_commons_lang.version}
#{@rule2//:commons_lang_commons_lang.version}
```
