### ISSUE TITLE
Have docs explain LIBRARY.root in more detail

### ISSUE THREAD

**Issue by plaird** [salesforce/pomgen#41]
We have a project internally with this structure:

foo-service-parent > foo-module > MVN-INF > LIBRARY.root
foo-service-parent > foo-service > MVN-INF > LIBRARY.root

This might be ok, but they probably want LIBRARY.root at the foo-service-parent level. But there are no docs I can point them at that explains the thinking behind where to locate that file. There is just a single line in the top-level README.

**Comment by simontoens** [comment]
@plaird FYI I have documented LIBRARY.root here: https://github.com/salesforce/pomgen/blob/master/docs/mdfiles.md#libraryroot

**Comment by plaird** [comment]
Looks great.
