### ISSUE TITLE
maven_jar is not working with latest bazel

### ISSUE THREAD

**Issue by kbaddepuri** [salesforce/pomgen#49]
When I install latest bazel and trying to build in my local machine, I am getting 
ERROR: /home/kbaddepuri/projects/opensource/pomgen/WORKSPACE:3:1: name 'maven_jar' is not defined
ERROR: /home/kbaddepuri/projects/opensource/pomgen/WORKSPACE:9:1: name 'maven_jar' is not defined
ERROR: /home/kbaddepuri/projects/opensource/pomgen/WORKSPACE:16:1: name 'maven_jar' is not defined
 error.

**Comment by btbuxton** [comment]
bazel deprecated maven_jar in versions after 1.2.1. Try "maven_install" branch - it should work with post-1.2.1 branches of bazel. Eventually, it will become master.

**Comment by simontoens** [comment]
Hi @kbaddepuri - our maven_install support is still a bit experimental (as Blaine has said, in the maven_install branch).  It works, but it assumes that you are using maven.artifact with exclusions set to `exclusions = ['*:*']` (similarly to how maven_jar behaved).  We are planning to remove this restriction. 

Please feel free to ping us with issues/questions.
