### ISSUE TITLE
Traverse through dependencies when -t is set

### ISSUE THREAD

**Issue by dylanShark** [salesforce/pomgen#99]
pomgen supports `-t` option for installing artifacts of a given library. For example, `bazel run @pomgen//maven -- -a install, -t examples/hello-world/juicer` will install the artifact of `examples/hello-world/juicer`.
However, the `-t` option does not traverse through the dependencies of the given library. Hence, dependencies of `examples/hello-world/juicer` maybe missing in local Maven repository. We want to make pomgen traverse through dependencies of the given library and install all necessary dependencies when a user uses `-t` option.

**Comment by simontoens** [comment]
Thanks for filing this @dylanShark.  Are you up for coming up with a proposal for a solution?

**Comment by dylanShark** [comment]
@simontoens Sure! Should I just post the proposal as a comment in this issue?

**Comment by simontoens** [comment]
@dylanShark yes, sounds good!  Thanks.
